repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile, black]
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/pylint
    rev: v2.12.1
    hooks:
      - id: pylint
        args: [--disable=all, --enable=C, --rcfile=pylint.rc]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
  - repo: https://gitlab.com/pycqa/flake8
      rev: 4.0.1
      hooks:
        - id: flake8