version: "3"
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    tty: true
  api:
    depends_on:
      - mysql
    container_name: python
    image: python
    platform: linux/x86_64
    build:
      dockerfile: dev.Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ../src:/src
      - ../documentation:/docs
    ports:
      - 8000:8000
      - 8001:8001